name: Nexmedis_Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Start application
        run: nohup npm start > app.log 2>&1 &
        env:
          PORT: 3000

      - name: Cek aplikasi berjalan
        run: netstat -ano | findstr :3000

      - name: Wait for application to be ready
        run: wait-on http://localhost:3000 && sleep 30

      - name: Check if server is up
        run: curl -I http://localhost:3000 || exit 1

      - name: Run Nexmedis_Test
        run: npx cypress run
        env:
          CI: true

      - name: Upload Cypress screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos